### ISSUE TITLE
Replace Refills gem.

### ISSUE THREAD

**Issue by matheusagcosta** [Helabs/pah#452]
One of these days, I've tried to use the latest features of refills and the `'generate refills:list'` was outdated.

Then, I opened an issue on the refills repo and someone said to replace the

```javascript
gem 'refills'
```
by 

```javascript
gem 'refills', github: 'thoughtbot/refills'.
```

This way, the list will be always updated.

More details here https://github.com/thoughtbot/refills/issues/185

**Comment by marcioj** [comment]
Taking the dependency directly from the github could include unstable things. Right know the build has errors https://github.com/thoughtbot/refills, so I am unsure whether we should include this by default ...

**Comment by TiuTalk** [comment]
I agree with @marcioj .. we can't trust on "undefined" versions from the GItHub master. At least, specify the working commit.

**Comment by TiuTalk** [comment]
Any update here, @matheusagcosta ?

**Comment by matheusagcosta** [comment]
@TiuTalk nope. There's an issue opened since October's 11. https://github.com/thoughtbot/refills/issues/141 but nothing's changed. :disappointed:
