### ISSUE TITLE
Integrate CodeClimate coverage badge.

### ISSUE THREAD

**Issue by rodrigopinto** [Helabs/pah#466]
https://codeclimate.com/tour/test-coverage

**Comment by maurogeorge** [comment]
@rodrigopinto we tried this in the past, but got no success trying the Aruba work with the simplecov. Take a look at https://github.com/Helabs/pah/pull/382.

I will close this for now, but if you know how to do that a PR is welcome :smile:

**Comment by rodrigopinto** [comment]
@maurogeorge Ok, I'll take a look. :)
