### ISSUE TITLE
Define heroku MAINTENANCE_URL on setup

### ISSUE THREAD

**Issue by rodrigopinto** [Helabs/pah#468]
I'd suggest to create a maintenance page that could be hosted at pah repository, and setup an url to it when creating a project via pah. :)

**Comment by rodrigopinto** [comment]
@maurogeorge @marano @marcioj @TiuTalk ??

**Comment by marano** [comment]
@rodrigopinto I support it!

**Comment by maurogeorge** [comment]
@rodrigopinto do you have used this before? I never used a custom url, since in most cases the downtime is so minimal.

Beside that, the MAINTENANCE_URL can be generated automatically or need to be one more question on pah?
