### ISSUE TITLE
Add Hound to the repo?

### ISSUE THREAD

**Issue by lunks** [Helabs/pah#472]
Hey guys and gals,

Have you heard about [Hound](https://houndci.com/)? It's a formatting check bot from ThoughtBot and it's free for open source projects. The [comment] I did would have been automated as soon as a PR is open to the project.

IMHO We should give it a try.

[comment]: https://github.com/Helabs/pah/pull/449#discussion_r27068383

**Comment by TiuTalk** [comment]
:+1:

**Comment by thiagogabriel** [comment]
No more double quotes :) :+1:

**Comment by marcioj** [comment]
:+1:

**Comment by TiuTalk** [comment]
I cannot setup/configure **Houd** because I'm now the owner of the project, just a collaborator :cry:

**Comment by andreanastacio** [comment]
ping @Helabs/owners

**Comment by TiuTalk** [comment]
@maurogeorge ?

**Comment by maurogeorge** [comment]
@TiuTalk I assigned this to me, when I have some time I will take a look.

**Comment by TiuTalk** [comment]
@maurogeorge thanks :+1:

**Comment by andreanastacio** [comment]
@TiuTalk @maurogeorge Done!

**Comment by maurogeorge** [comment]
@andreanastacio Thanks :tada:

**Comment by lunks** [comment]
:clap:

**Comment by TiuTalk** [comment]
:clap:
