### ISSUE TITLE
Consider the use of .editorconfig

### ISSUE THREAD

**Issue by marcioj** [Helabs/pah#476]
.editorconfig is a generic file which make the editor follow some style/format conditions. Ex: tabs instead of spaces, no trailing spaces etc. Would be interesting to generated an project including it with our conventions.
What you guys think about it?

**Comment by marcioj** [comment]
More info in http://editorconfig.org/

**Comment by TiuTalk** [comment]
@marcioj I totally agree with this, and I've suggested it in the past, not sure why it's not being used.

Anyway, can you provide a PR?

**Comment by TiuTalk** [comment]
Oh, here it is: https://github.com/Helabs/pah/issues/261

**Comment by lunks** [comment]
:+1:

**Comment by rodrigopinto** [comment]
@marcioj Any news about it?

**Comment by eduardofiorezi** [comment]
Guys, this discussion is already very old. Let's close and discuss in a future PR :)
