### ISSUE TITLE
Wrong port used in config/puma

### ISSUE THREAD

**Issue by marcioj** [Helabs/pah#485]
ENV['PORT'] in config/puma returns 5000 even when PORT: 3000 in .env

**Comment by TiuTalk** [comment]
The `.env` file is read by the `dotenv` gem, not your system/RVM... it shouldn't get the port 3000 if you have this kind of setup.

The `ENV['PORT']` on **config/puma.rb** is used by production environments, where you have the ENVs set via the system (like `heroku config:set`) and not `.env` files.

**Comment by marcioj** [comment]
@TiuTalk so If I am in my development machine and run `foreman start` the port should be 5000? I find this confuse. Where the port 5000 comes from?

**Comment by TiuTalk** [comment]
The default port on `config/puma.rb` is 3000:

https://github.com/Helabs/pah/blob/master/lib/pah/files/config/puma.rb

The default por of **foreman** is 5000:

> Your web process loads on port 5000 because this is what Foreman provides as a default in the $PORT env var.

https://devcenter.heroku.com/articles/procfile#developing-locally-with-foreman

**Comment by andreanastacio** [comment]
ping @marciliojrs
