### ISSUE TITLE
Include sprockets-es6

### ISSUE THREAD

**Issue by marcioj** [Helabs/pah#490]
Now that sprockets-es6 has support for sprockets 3, [see this PR](https://github.com/TannerRogalsky/sprockets-es6/pull/2), I believe we can add it to pah and take advance of es-next features today. It's also good to remember that with es6 you can still write the old syntax. I.e: `var`, `function` etc. So any existing script in es5 just works.

This issue is not related with any effort to create a development workflow like #487, it's just to enhance the syntax.

//cc @Helabs/developers

**Comment by maurogeorge** [comment]
@marcioj I have some questions about it:

- This will work with all the bourbon family?
- This will change the way we need to [write js to our app](https://github.com/TannerRogalsky/sprockets-es6#asset-manifests-required-for-precompiling)? I mean, beside the manifest I need to do some other stuff before add a new JS file
- You are using this on a app today? If not, what you think about using this before we add to pah?

**Comment by marcioj** [comment]
> This will work with all the bourbon family?

Yes

> This will change the way we need to write js to our app? I mean, beside the manifest I need to do some other stuff before add a new JS file

Yes. The javascripts won't be evaluated in a global scope since they will use es6 modules. Instead you will need to require what you want. To make things simple I believe I will add something like this:

**app/assets/javascripts/application.js**

```js
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require_tree .

$(document).on('page:load ready', function() {
  require('main.js')['default'];
});
```

**app/assets/javascripts/main.es6**

```js
import otherStuff from './other_file'

export default function() {
  // main entry point put your scripts here, import other things using `import` etc
 otherStuff();
}
```

I intend to just make the files ending with .es6 be processed in this way.  To make it clear that they are transpiled. Creating files ending with .js will work in the same way as today.

> You are using this on a app today? If not, what you think about using this before we add to pah?

Make sense, I have not used it yet. If someone start a new project before me and want to use this, ping me.

**Comment by maurogeorge** [comment]
Closing, since we are not using this on a real app.
Later we can comeback to this issue.
