### ISSUE TITLE
Upgrade rack-timeout to use the heroku version

### ISSUE THREAD

**Issue by maurogeorge** [Helabs/pah#492]
Today we use a fork https://github.com/kch/rack-timeout, that actually redirect to the heroku gem.

I think we are good to use the heroku gem directly from the rubygems.

I really don't remember why we use a specific hash on the fork. Any idea @tomasmuller @TiuTalk ?

**Comment by tomasmuller** [comment]
@maurogeorge once upon a time.. https://github.com/heroku/rack-timeout/issues/41 :smile:

**Comment by maurogeorge** [comment]
@tomasmuller cool, it seens that it is fixed, so we are good to go.

**Comment by thiagogabriel** [comment]
My project is using '0.2.4' in production and I'm not seeing any problem.

**Comment by thiagogabriel** [comment]
Closed because rack-timeout was removed https://github.com/Helabs/pah/pull/495
